application: postupnow-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /static
  static_dir: static

- url: /.*
  script: postupnow.application



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
